export const
        ADD_MESSAGE = 'ADD_MESSAGE',
        LOAD_MESSAGES_PENDING = 'LOAD_MESSAGES_PENDING',
        LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS',
        LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR',
        ADD_USER = 'ADD_USER';